EMAIL = "23f1002875@ds.study.iitm.ac.in"
AIPIPE_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjIzZjEwMDI4NzVAZHMuc3R1ZHkuaWl0bS5hYy5pbiIsImlhdCI6MTc4Mzg1OTczOSwiaXNzIjoiaHR0cHM6Ly9haXBpcGUub3JnIiwiYXVkIjoiYWlwaXBlLWFwaSIsImV4cCI6MTc4NDQ2NDUzOX0.UMdjCFHEQmwFVceJt9IIlV56lFFRsMEPZCiTChnlp9g"
AIPIPE_BASE = "https://aipipe.org/openai/v1"
TEXT_MODEL = "gpt-4o-mini"
VISION_MODEL = "gpt-4.1"
EMBED_MODEL = "text-embedding-3-small"
